# Generated by Django 4.1 on 2022-10-26 16:15

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('reg_id', models.AutoField(primary_key=True, serialize=False)),
                ('FIO', models.CharField(blank=True, max_length=1000, null=True)),
                ('article_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('abstract', models.CharField(blank=True, max_length=1000, null=True)),
                ('thesis', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
